default:
  image:
    # Specify docker image to be used to execute the pipeline inside
    name: baselime/baselime:latest
    entrypoint: [""]

variables:
  BASELIME_API_KEY: $BASELIME_API_KEY

stages:
  - plan
  - push
  - report
plan:
  stage: plan
  script:
    # Show the changes to be pushed
    - echo no | baselime push --c .baselime

push:
  stage: push
  needs:
    - plan
  # Add "manual" to require user to confirm before pushing the configuration changes
  when: manual
  allow_failure: true
  script:
    - baselime push -y --c .baselime

report:
  stage: report
  needs:
    - push
  script:
    # Produces report of your alerts with the latest changes applied.
    - baselime report --c .baselime