// make sure to add "baselime-api-key" to your Jenkins credentials prior to running this pipeline

pipeline {
    agent any

    stages {

        stage("Plan") {
            // We need to specify our agent to be docker using Baselime image
            agent {
                docker {
                    image 'baselime/baselime:latest'
                    args '--entrypoint='
                    reuseNode true
                }
            }

            environment {
                // Required: in order to authenticate with Baselime's API
                BASELIME_API_KEY = credentials('baselime-api-key')
            }

            steps {
                // This will show us the changes to be made to the observability without actually applying the changes
                sh 'echo "no" | baselime push --c .baselime'
            }
        }

        stage("Push and Report") {

            // We need to specify our agent to be docker using Baselime image
            agent {
                docker {
                    image 'baselime/baselime:latest'
                    args '--entrypoint='
                    reuseNode true
                }
            }

            environment {
                // Required: in order to authenticate with Baselime's API
                BASELIME_API_KEY = credentials('baselime-api-key')
            }

            // Jenkins will ask for confirmation before continuing
            input {
                message "Do you want to push the changes?"
                ok "Yes"
            }

            steps {
                // This step will apply the changes to the observability
                sh 'baselime push -y --c .baselime'
                // This step will collect and print report of the alerts and their statuses for your service
                sh 'baselime report --c .baselime'
            }
        }
    }
}